version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env

  mysql:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    ports:
      - 8080:80

volumes:
  mysqldata: {}
