version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    restart: unless-stopped
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      MYSQL_URL: "mysql://root:laYzFqVRqEmavMRfxctHnKAIgmRvTClY@mysql:3306/railway"
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "railway"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "laYzFqVRqEmavMRfxctHnKAIgmRvTClY"
      MYSQL_CHARSET: "utf8mb4"
    restart: unless-stopped
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "laYzFqVRqEmavMRfxctHnKAIgmRvTClY"
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "laYzFqVRqEmavMRfxctHnKAIgmRvTClY"
      MYSQL_DATABASE: "railway"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysqldata: {}
